name: file_previewer
description: Generate a thumbnail for a file based on the file extension. Uses the native files previewer on iOS.
version: 0.1.0
repository: https://github.com/DutchCodingCompany/file_preview

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdfx:
    git:
      url: https://github.com/ScerIO/packages.flutter.git
      path: packages/pdfx
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img.png
  plugin:
    platforms:
      android:
        package: com.dcc.file_previewer
        pluginClass: FilePreviewerPlugin
      ios:
        pluginClass: FilePreviewerPlugin
